apiVersion: v1
kind: ResourceQuota
metadata:
  name: dockworker-quota
  namespace: dockworker-runners
spec:
  hard:
    requests.cpu: "32"
    requests.memory: "64Gi"
    requests.ephemeral-storage: "500Gi"
    limits.cpu: "64"
    limits.memory: "128Gi"
    limits.ephemeral-storage: "1000Gi"
    pods: "100"
  scopeSelector:
    matchExpressions:
      - operator: In
        scopeName: PriorityClass
        values: ["default"]
